version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: SmartAppDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartapi
    ports:
      - "5086:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

volumes:
  postgres_data:
