events { }
http {
    server {
        listen 80;
        server_name smartapp.local;
        location / {
            proxy_pass http://smartapp_client:80;
            proxy_set_header Host $host;
        }
    }
    server {
        listen 80;
        server_name smartwebapi.local;
        location / {
            proxy_pass http://smart_api:8080;
            proxy_set_header Host $host;
        }
    }
    server {
        listen 80;
        server_name keycloak.local;
        location / {
            proxy_pass http://keycloak:8080;
            proxy_set_header Host $host;
        }
    }
}
