apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  API_CONNECTION: Host=postgres.app.svc.cluster.local;Database=postgres;Username=postgres;Password=30730f5weg2
  API_BASE_URL: http://dotnet-api.app.svc.cluster.local
